/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shape.stacker;

import shape.stacker.shape.ShapeStacker;
import shape.stacker.shape.shapes.Circle;
import shape.stacker.shape.shapes.Rectangle;
import shape.stacker.shape.shapes.Square;
import shape.stacker.shape.shapes.Triangle;

public class App {
    public static void main(String[] args) {

        ShapeStacker shapeStacker = new ShapeStacker();
        shapeStacker.addShape(new Triangle(20, 22, 22));
        shapeStacker.addShape(new Square(10));
        shapeStacker.addShape(new Circle(7));


        String result = shapeStacker.stack();
        System.out.println(result);
    }
}
